### ISSUE TITLE
error report IPAdapterApply not found

### ISSUE THREAD

**Issue by quqiufeng** [fofr/cog-become-image#6]
![Uploading 微信截图_20240326141718.png…]()

**Comment by quqiufeng** [comment]
error message ：

When loading the graph, the following node types were not found:
IPAdapterApply
Nodes that have failed to load will show as red on the graph.

**Comment by YoucanBaby** [comment]
Replace `IPAdatper Advanced` with `IPAdapterApply`

**Comment by quqiufeng** [comment]
> Replace `IPAdatper Advanced` with `IPAdapterApply`

do not work

**Comment by quqiufeng** [comment]
Error occurred when executing IPAdapterAdvanced:

'CrossAttentionPatch' object has no attribute 'add'

File "G:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute



output_data, output_ui = get_output_data(obj, input_data_all)
File "G:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "G:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "G:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 711, in apply_ipadapter
work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args)
File "G:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 404, in ipadapter_execute
set_model_patch_replace(model, patch_kwargs, ("input", id, index))
File "G:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 153, in set_model_patch_replace
to["patches_replace"]["attn2"][key].add(ipadapter_attention, **patch_kwargs)


when i select  xl  ipadapter model  this not work ，sd1.5 works  but not good

**Comment by CoUIfy** [comment]
Did you find ipadaptro apply yet?

**Comment by quqiufeng** [comment]
![微信截图_20240606191852](https://github.com/fofr/cog-become-image/assets/839168/5958b085-4472-4327-9797-9f065c6b2bf2)

thank u for your help
i fix this !

**Comment by CoUIfy** [comment]
> ![微信截图_20240606191852](https://private-user-images.githubusercontent.com/839168/337242288-5958b085-4472-4327-9797-9f065c6b2bf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Nzg5NjUsIm5iZiI6MTcxNzY3ODY2NSwicGF0aCI6Ii84MzkxNjgvMzM3MjQyMjg4LTU5NThiMDg1LTQ0NzItNDMyNy05Nzk3LTlmMDY1YzZiMmJmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQxMjU3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjFjZThiZjg3NTI0N2RkNmNhN2FkZmU0ODg0ZDQ2NTk2ZjM3MzMyMTk4ZTYxZGExYjc0NDUyMmJhZWU4NjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JBcPH2PjCcPsY6vRwV5cMNGXfzzynNDEi08WevJZWys)
> 
> thank u for your help i fix this !

Can you send me your JSON FILE please ? :)

**Comment by CoUIfy** [comment]
@quqiufeng
